/** Complete incorporated municipalities for Georgia and New Jersey. */

export const GA_CITIES = [
  'Abbeville',
  'Acworth',
  'Adairsville',
  'Adel',
  'Adrian',
  'Ailey',
  'Alamo',
  'Alapaha',
  'Albany',
  'Aldora',
  'Allenhurst',
  'Allentown',
  'Alma',
  'Alpharetta',
  'Alston',
  'Alto',
  'Ambrose',
  'Americus',
  'Andersonville',
  'Arabi',
  'Aragon',
  'Arcade',
  'Argyle',
  'Arlington',
  'Arnoldsville',
  'Ashburn',
  'Athens',
  'Atlanta',
  'Attapulgus',
  'Auburn',
  'Augusta',
  'Austell',
  'Avalon',
  'Avera',
  'Avondale Estates',
  'Baconton',
  'Bainbridge',
  'Baldwin',
  'Ball Ground',
  'Barnesville',
  'Bartow',
  'Barwick',
  'Baxley',
  'Bellville',
  'Berkeley Lake',
  'Berlin',
  'Bethlehem',
  'Between',
  'Bishop',
  'Blackshear',
  'Blairsville',
  'Blakely',
  'Bloomingdale',
  'Blue Ridge',
  'Bluffton',
  'Blythe',
  'Bogart',
  'Boston',
  'Bostwick',
  'Bowdon',
  'Bowersville',
  'Bowman',
  'Braselton',
  'Braswell',
  'Bremen',
  'Brinson',
  'Bronwood',
  'Brookhaven',
  'Brooklet',
  'Brooks',
  'Broxton',
  'Brunswick',
  'Buchanan',
  'Buckhead',
  'Buena Vista',
  'Buford',
  'Butler',
  'Byromville',
  'Byron',
  'Cadwell',
  'Cairo',
  'Calhoun',
  'Camak',
  'Camilla',
  'Canon',
  'Canton',
  'Carl',
  'Carlton',
  'Carnesville',
  'Carrollton',
  'Cartersville',
  'Cave Spring',
  'Cecil',
  'Cedartown',
  'Centerville',
  'Centralhatchee',
  'Chamblee',
  'Chatsworth',
  'Chattahoochee Hills',
  'Chauncey',
  'Chester',
  'Chickamauga',
  'Clarkesville',
  'Clarkston',
  'Claxton',
  'Clayton',
  'Clermont',
  'Cleveland',
  'Climax',
  'Cobbtown',
  'Cochran',
  'Cohutta',
  'Colbert',
  'College Park',
  'Collins',
  'Colquitt',
  'Columbus',
  'Comer',
  'Commerce',
  'Concord',
  'Conyers',
  'Coolidge',
  'Cordele',
  'Cornelia',
  'Covington',
  'Crawford',
  'Crawfordville',
  'Culloden',
  'Cumming',
  'Cusseta',
  'Cuthbert',
  'Dacula',
  'Dahlonega',
  'Daisy',
  'Dallas',
  'Dalton',
  'Damascus',
  'Danielsville',
  'Danville',
  'Darien',
  'Dasher',
  'Davisboro',
  'Dawson',
  'Dawsonville',
  'De Soto',
  'Dearing',
  'Decatur',
  'Deepstep',
  'Demorest',
  'Denton',
  'Dexter',
  'Dillard',
  'Doerun',
  'Donalsonville',
  'Dooling',
  'Doraville',
  'Douglas',
  'Douglasville',
  'Du Pont',
  'Dublin',
  'Dudley',
  'Duluth',
  'Dunwoody',
  'East Dublin',
  'East Ellijay',
  'East Point',
  'Eastman',
  'Eatonton',
  'Edge Hill',
  'Edison',
  'Elberton',
  'Ellaville',
  'Ellenton',
  'Ellijay',
  'Emerson',
  'Enigma',
  'Ephesus',
  'Eton',
  'Euharlee',
  'Fairburn',
  'Fairmount',
  'Fargo',
  'Fayetteville',
  'Fitzgerald',
  'Flemington',
  'Flovilla',
  'Flowery Branch',
  'Folkston',
  'Forest Park',
  'Forsyth',
  'Fort Gaines',
  'Fort Oglethorpe',
  'Fort Valley',
  'Franklin',
  'Franklin Springs',
  'Funston',
  'Gainesville',
  'Garden City',
  'Garfield',
  'Gay',
  'Geneva',
  'Georgetown',
  'Gibson',
  'Gillsville',
  'Girard',
  'Glennville',
  'Glenwood',
  'Good Hope',
  'Gordon',
  'Graham',
  'Grantville',
  'Gray',
  'Grayson',
  'Greensboro',
  'Greenville',
  'Griffin',
  'Grovetown',
  'Gumbranch',
  'Guyton',
  'Hagan',
  'Hahira',
  'Hamilton',
  'Hampton',
  'Hapeville',
  'Haralson',
  'Harlem',
  'Harrison',
  'Hartwell',
  'Hawkinsville',
  'Hazlehurst',
  'Helen',
  'Hephzibah',
  'Hiawassee',
  'Higgston',
  'Hiltonia',
  'Hinesville',
  'Hiram',
  'Hoboken',
  'Hogansville',
  'Holly Springs',
  'Homeland',
  'Homer',
  'Homerville',
  'Hoschton',
  'Hull',
  'Ideal',
  'Ila',
  'Iron City',
  'Irwinton',
  'Ivey',
  'Jackson',
  'Jacksonville',
  'Jakin',
  'Jasper',
  'Jefferson',
  'Jeffersonville',
  'Jenkinsburg',
  'Jersey',
  'Jesup',
  'Johns Creek',
  'Jonesboro',
  'Junction City',
  'Kennesaw',
  'Keysville',
  'Kingsland',
  'Kingston',
  'Kite',
  'LaFayette',
  'LaGrange',
  'Lake City',
  'Lake Park',
  'Lakeland',
  'Lavonia',
  'Lawrenceville',
  'Leary',
  'Leesburg',
  'Lenox',
  'Leslie',
  'Lexington',
  'Lilburn',
  'Lilly',
  'Lincolnton',
  'Lithonia',
  'Locust Grove',
  'Loganville',
  'Lone Oak',
  'Lookout Mountain',
  'Louisville',
  'Lovejoy',
  'Ludowici',
  'Lula',
  'Lumber City',
  'Lumpkin',
  'Luthersville',
  'Lyerly',
  'Lyons',
  'Mableton',
  'Macon',
  'Madison',
  'Manassas',
  'Manchester',
  'Mansfield',
  'Marietta',
  'Marshallville',
  'Martin',
  'Maxeys',
  'Maysville',
  'McCaysville',
  'McDonough',
  'McIntyre',
  'McRae–Helena',
  'Meansville',
  'Meigs',
  'Menlo',
  'Metter',
  'Midville',
  'Midway',
  'Milan',
  'Milledgeville',
  'Millen',
  'Milner',
  'Milton',
  'Mitchell',
  'Molena',
  'Monroe',
  'Montezuma',
  'Monticello',
  'Montrose',
  'Moreland',
  'Morgan',
  'Morganton',
  'Morrow',
  'Morven',
  'Moultrie',
  'Mount Airy',
  'Mount Vernon',
  'Mount Zion',
  'Mountain City',
  'Mountain Park',
  'Nahunta',
  'Nashville',
  'Nelson',
  'Newborn',
  'Newington',
  'Newnan',
  'Newton',
  'Nicholls',
  'Nicholson',
  'Norcross',
  'Norman Park',
  'North High Shoals',
  'Norwood',
  'Nunez',
  'Oak Park',
  'Oakwood',
  'Ochlocknee',
  'Ocilla',
  'Oconee',
  'Odum',
  'Offerman',
  'Oglethorpe',
  'Oliver',
  'Omega',
  'Orchard Hill',
  'Oxford',
  'Palmetto',
  'Parrott',
  'Patterson',
  'Pavo',
  'Peachtree City',
  'Peachtree Corners',
  'Pearson',
  'Pelham',
  'Pembroke',
  'Pendergrass',
  'Perry',
  'Pine Lake',
  'Pine Mountain',
  'Pinehurst',
  'Pineview',
  'Pitts',
  'Plains',
  'Plainville',
  'Pooler',
  'Port Wentworth',
  'Portal',
  'Porterdale',
  'Poulan',
  'Powder Springs',
  'Pulaski',
  'Quitman',
  'Ranger',
  'Ray City',
  'Rayle',
  'Rebecca',
  'Register',
  'Reidsville',
  'Remerton',
  'Rentz',
  'Resaca',
  'Rest Haven',
  'Reynolds',
  'Rhine',
  'Riceboro',
  'Richland',
  'Richmond Hill',
  'Riddleville',
  'Rincon',
  'Ringgold',
  'Riverdale',
  'Roberta',
  'Rochelle',
  'Rockmart',
  'Rocky Ford',
  'Rome',
  'Roopville',
  'Rossville',
  'Roswell',
  'Royston',
  'Rutledge',
  'Sale City',
  'Sandersville',
  'Sandy Springs',
  'Santa Claus',
  'Sardis',
  'Sasser',
  'Savannah',
  'Scotland',
  'Screven',
  'Senoia',
  'Shady Dale',
  'Sharon',
  'Sharpsburg',
  'Shellman',
  'Shiloh',
  'Siloam',
  'Sky Valley',
  'Smithville',
  'Smyrna',
  'Snellville',
  'Social Circle',
  'Soperton',
  'South Fulton',
  'Sparks',
  'Sparta',
  'Springfield',
  'St. Marys',
  'Stapleton',
  'Statesboro',
  'Statham',
  'Stillmore',
  'Stockbridge',
  'Stone Mountain',
  'Stonecrest',
  'Sugar Hill',
  'Summertown',
  'Summerville',
  'Sumner',
  'Sunny Side',
  'Surrency',
  'Suwanee',
  'Swainsboro',
  'Sycamore',
  'Sylvania',
  'Sylvester',
  'Talbotton',
  'Talking Rock',
  'Tallapoosa',
  'Tallulah Falls',
  'Talmo',
  'Tarrytown',
  'Taylorsville',
  'Temple',
  'Tennille',
  'Thomaston',
  'Thomasville',
  'Thomson',
  'Thunderbolt',
  'Tifton',
  'Tiger',
  'Tignall',
  'Toccoa',
  'Toomsboro',
  'Trenton',
  'Trion',
  'Tucker',
  'Tunnel Hill',
  'Turin',
  'Twin City',
  'Ty Ty',
  'Tybee Island',
  'Tyrone',
  'Unadilla',
  'Union City',
  'Union Point',
  'Uvalda',
  'Valdosta',
  'Varnell',
  'Vernonburg',
  'Vidalia',
  'Vidette',
  'Vienna',
  'Villa Rica',
  'Waco',
  'Wadley',
  'Waleska',
  'Walnut Grove',
  'Walthourville',
  'Warm Springs',
  'Warner Robins',
  'Warrenton',
  'Warwick',
  'Washington',
  'Watkinsville',
  'Waverly Hall',
  'Waycross',
  'Waynesboro',
  'West Point',
  'Whigham',
  'White',
  'White Plains',
  'Whitesburg',
  'Willacoochee',
  'Williamson',
  'Winder',
  'Winterville',
  'Woodbine',
  'Woodbury',
  'Woodland',
  'Woodstock',
  'Woodville',
  'Woolsey',
  'Wrens',
  'Wrightsville',
  'Yatesville',
  'Young Harris',
  'Zebulon',
] as const

export const NJ_CITIES = [
  'Aberdeen',
  'Absecon',
  'Alexandria',
  'Allamuchy',
  'Allendale',
  'Allenhurst',
  'Allentown',
  'Alloway',
  'Alpha',
  'Alpine',
  'Andover',
  'Andover Borough',
  'Asbury Park',
  'Atlantic City',
  'Atlantic Highlands',
  'Audubon',
  'Audubon Park',
  'Avalon',
  'Avon-by-the-Sea',
  'Barnegat',
  'Barnegat Light',
  'Barrington',
  'Bass River',
  'Bay Head',
  'Bayonne',
  'Beach Haven',
  'Beachwood',
  'Bedminster',
  'Belleville',
  'Bellmawr',
  'Belmar',
  'Belvidere',
  'Bergenfield',
  'Berkeley',
  'Berkeley Heights',
  'Berlin',
  'Berlin Borough',
  'Bernards',
  'Bernardsville',
  'Bethlehem',
  'Beverly',
  'Blairstown',
  'Bloomfield',
  'Bloomingdale',
  'Bloomsbury',
  'Bogota',
  'Boonton',
  'Boonton Town',
  'Bordentown',
  'Bordentown City',
  'Bound Brook',
  'Bradley Beach',
  'Branchburg',
  'Branchville',
  'Brick',
  'Bridgeton',
  'Bridgewater',
  'Brielle',
  'Brigantine',
  'Brooklawn',
  'Buena',
  'Buena Vista',
  'Burlington',
  'Burlington City',
  'Butler',
  'Byram',
  'Caldwell',
  'Califon',
  'Camden',
  'Cape May',
  'Cape May Point',
  'Carlstadt',
  'Carneys Point',
  'Carteret',
  'Cedar Grove',
  'Chatham',
  'Chatham Borough',
  'Cherry Hill',
  'Chesilhurst',
  'Chester',
  'Chester Borough',
  'Chesterfield',
  'Cinnaminson',
  'Clark',
  'Clayton',
  'Clementon',
  'Cliffside Park',
  'Clifton',
  'Clinton',
  'Clinton Town',
  'Closter',
  'Collingswood',
  'Colts Neck',
  'Commercial',
  'Corbin City',
  'Cranbury',
  'Cranford',
  'Cresskill',
  'Deal',
  'Deerfield',
  'Delanco',
  'Delaware',
  'Delran',
  'Demarest',
  'Dennis',
  'Denville',
  'Deptford',
  'Dover',
  'Downe',
  'Dumont',
  'Dunellen',
  'Eagleswood',
  'East Amwell',
  'East Brunswick',
  'East Greenwich',
  'East Hanover',
  'East Newark',
  'East Orange',
  'East Rutherford',
  'East Windsor',
  'Eastampton',
  'Eatontown',
  'Edgewater',
  'Edgewater Park',
  'Edison',
  'Egg Harbor',
  'Egg Harbor City',
  'Elizabeth',
  'Elk',
  'Elmer',
  'Elmwood Park',
  'Elsinboro',
  'Emerson',
  'Englewood',
  'Englewood Cliffs',
  'Englishtown',
  'Essex Fells',
  'Estell Manor',
  'Evesham',
  'Ewing',
  'Fair Haven',
  'Fair Lawn',
  'Fairfield',
  'Fairview',
  'Fanwood',
  'Far Hills',
  'Farmingdale',
  'Fieldsboro',
  'Flemington',
  'Florence',
  'Florham Park',
  'Folsom',
  'Fort Lee',
  'Frankford',
  'Franklin',
  'Franklin Borough',
  'Franklin Lakes',
  'Fredon',
  'Freehold',
  'Freehold Borough',
  'Frelinghuysen',
  'Frenchtown',
  'Galloway',
  'Garfield',
  'Garwood',
  'Gibbsboro',
  'Glassboro',
  'Glen Gardner',
  'Glen Ridge',
  'Glen Rock',
  'Gloucester',
  'Gloucester City',
  'Green',
  'Green Brook',
  'Greenwich',
  'Guttenberg',
  'Hackensack',
  'Hackettstown',
  'Haddon',
  'Haddon Heights',
  'Haddonfield',
  'Hainesport',
  'Haledon',
  'Hamburg',
  'Hamilton',
  'Hammonton',
  'Hampton',
  'Hampton Borough',
  'Hanover',
  'Harding',
  'Hardwick',
  'Hardyston',
  'Harmony',
  'Harrington Park',
  'Harrison',
  'Harvey Cedars',
  'Hasbrouck Heights',
  'Haworth',
  'Hawthorne',
  'Hazlet',
  'Helmetta',
  'Hi-Nella',
  'High Bridge',
  'Highland Park',
  'Highlands',
  'Hightstown',
  'Hillsborough',
  'Hillsdale',
  'Hillside',
  'Ho-Ho-Kus',
  'Hoboken',
  'Holland',
  'Holmdel',
  'Hopatcong',
  'Hope',
  'Hopewell',
  'Hopewell Borough',
  'Howell',
  'Independence',
  'Interlaken',
  'Irvington',
  'Island Heights',
  'Jackson',
  'Jamesburg',
  'Jefferson',
  'Jersey City',
  'Keansburg',
  'Kearny',
  'Kenilworth',
  'Keyport',
  'Kingwood',
  'Kinnelon',
  'Knowlton',
  'Lacey',
  'Lafayette',
  'Lake Como',
  'Lakehurst',
  'Lakewood',
  'Lambertville',
  'Laurel Springs',
  'Lavallette',
  'Lawnside',
  'Lawrence',
  'Lebanon',
  'Lebanon Borough',
  'Leonia',
  'Liberty',
  'Lincoln Park',
  'Linden',
  'Lindenwold',
  'Linwood',
  'Little Egg Harbor',
  'Little Falls',
  'Little Ferry',
  'Little Silver',
  'Livingston',
  'Loch Arbour',
  'Lodi',
  'Logan',
  'Long Beach',
  'Long Branch',
  'Long Hill',
  'Longport',
  'Lopatcong',
  'Lower',
  'Lower Alloways Creek',
  'Lumberton',
  'Lyndhurst',
  'Madison',
  'Magnolia',
  'Mahwah',
  'Manalapan',
  'Manasquan',
  'Manchester',
  'Mannington',
  'Mansfield',
  'Mantoloking',
  'Mantua',
  'Manville',
  'Maple Shade',
  'Maplewood',
  'Margate City',
  'Marlboro',
  'Matawan',
  'Maurice River',
  'Maywood',
  'Medford',
  'Medford Lakes',
  'Mendham',
  'Mendham Borough',
  'Merchantville',
  'Metuchen',
  'Middle',
  'Middlesex',
  'Middletown',
  'Midland Park',
  'Milford',
  'Millburn',
  'Millstone',
  'Millstone Borough',
  'Milltown',
  'Millville',
  'Mine Hill',
  'Monmouth Beach',
  'Monroe',
  'Montague',
  'Montclair',
  'Montgomery',
  'Montvale',
  'Montville',
  'Moonachie',
  'Moorestown',
  'Morris',
  'Morris Plains',
  'Morristown',
  'Mount Arlington',
  'Mount Ephraim',
  'Mount Holly',
  'Mount Laurel',
  'Mount Olive',
  'Mountain Lakes',
  'Mountainside',
  'Mullica',
  'National Park',
  'Neptune',
  'Neptune City',
  'Netcong',
  'New Brunswick',
  'New Hanover',
  'New Milford',
  'New Providence',
  'Newark',
  'Newfield',
  'Newton',
  'North Arlington',
  'North Bergen',
  'North Brunswick',
  'North Caldwell',
  'North Haledon',
  'North Hanover',
  'North Plainfield',
  'North Wildwood',
  'Northfield',
  'Northvale',
  'Norwood',
  'Nutley',
  'Oakland',
  'Oaklyn',
  'Ocean',
  'Ocean City',
  'Ocean Gate',
  'Oceanport',
  'Ogdensburg',
  'Old Bridge',
  'Old Tappan',
  'Oldmans',
  'Oradell',
  'Orange',
  'Oxford',
  'Palisades Park',
  'Palmyra',
  'Paramus',
  'Park Ridge',
  'Parsippany-Troy Hills',
  'Passaic',
  'Paterson',
  'Paulsboro',
  'Peapack and Gladstone',
  'Pemberton',
  'Pemberton Borough',
  'Pennington',
  'Penns Grove',
  'Pennsauken',
  'Pennsville',
  'Pequannock',
  'Perth Amboy',
  'Phillipsburg',
  'Pilesgrove',
  'Pine Beach',
  'Pine Hill',
  'Piscataway',
  'Pitman',
  'Pittsgrove',
  'Plainfield',
  'Plainsboro',
  'Pleasantville',
  'Plumsted',
  'Pohatcong',
  'Point Pleasant',
  'Point Pleasant Beach',
  'Pompton Lakes',
  'Port Republic',
  'Princeton',
  'Prospect Park',
  'Quinton',
  'Rahway',
  'Ramsey',
  'Randolph',
  'Raritan',
  'Readington',
  'Red Bank',
  'Ridgefield',
  'Ridgefield Park',
  'Ridgewood',
  'Ringwood',
  'River Edge',
  'River Vale',
  'Riverdale',
  'Riverside',
  'Riverton',
  'Robbinsville',
  'Rochelle Park',
  'Rockaway',
  'Rockaway Borough',
  'Rockleigh',
  'Rocky Hill',
  'Roosevelt',
  'Roseland',
  'Roselle',
  'Roselle Park',
  'Roxbury',
  'Rumson',
  'Runnemede',
  'Rutherford',
  'Saddle Brook',
  'Saddle River',
  'Salem',
  'Sandyston',
  'Sayreville',
  'Scotch Plains',
  'Sea Bright',
  'Sea Girt',
  'Sea Isle City',
  'Seaside Heights',
  'Seaside Park',
  'Secaucus',
  'Shamong',
  'Shiloh',
  'Ship Bottom',
  'Shrewsbury',
  'Shrewsbury Borough',
  'Somerdale',
  'Somers Point',
  'Somerville',
  'South Amboy',
  'South Bound Brook',
  'South Brunswick',
  'South Hackensack',
  'South Harrison',
  'South Orange',
  'South Plainfield',
  'South River',
  'South Toms River',
  'Southampton',
  'Sparta',
  'Spotswood',
  'Spring Lake',
  'Spring Lake Heights',
  'Springfield',
  'Stafford',
  'Stanhope',
  'Stillwater',
  'Stockton',
  'Stone Harbor',
  'Stow Creek',
  'Stratford',
  'Summit',
  'Surf City',
  'Sussex',
  'Swedesboro',
  'Tabernacle',
  'Tavistock',
  'Teaneck',
  'Tenafly',
  'Teterboro',
  'Tewksbury',
  'Tinton Falls',
  'Toms River',
  'Totowa',
  'Trenton',
  'Tuckerton',
  'Union',
  'Union Beach',
  'Union City',
  'Upper',
  'Upper Deerfield',
  'Upper Freehold',
  'Upper Pittsgrove',
  'Upper Saddle River',
  'Ventnor City',
  'Vernon',
  'Verona',
  'Victory Gardens',
  'Vineland',
  'Voorhees',
  'Waldwick',
  'Wall',
  'Wallington',
  'Walpack',
  'Wanaque',
  'Wantage',
  'Warren',
  'Washington',
  'Washington Borough',
  'Watchung',
  'Waterford',
  'Wayne',
  'Weehawken',
  'Wenonah',
  'West Amwell',
  'West Caldwell',
  'West Cape May',
  'West Deptford',
  'West Long Branch',
  'West Milford',
  'West New York',
  'West Orange',
  'West Wildwood',
  'West Windsor',
  'Westampton',
  'Westfield',
  'Westville',
  'Westwood',
  'Weymouth',
  'Wharton',
  'White',
  'Wildwood',
  'Wildwood Crest',
  'Willingboro',
  'Winfield',
  'Winslow',
  'Wood-Ridge',
  'Woodbine',
  'Woodbridge',
  'Woodbury',
  'Woodbury Heights',
  'Woodcliff Lake',
  'Woodland',
  'Woodland Park',
  'Woodlynne',
  'Woodstown',
  'Woolwich',
  'Wrightstown',
  'Wyckoff',
] as const
